"""
report/generator.py — Weekly intelligence report generator

This is the system's primary output artifact. Every week it produces a
structured briefing that answers three questions:

  1. What did I observe? (signals, sources, volume)
  2. What does it mean? (opportunities, entities, patterns)
  3. What should I do next? (ranked actions with evidence)

The report is stored in the database (reports table) and served via the API.
It is also the natural input for future modules: the Business Generator would
read a report to draft business model outlines; the Execution Agent would read
it to draft outreach messages.

Design constraint:
  Every sentence in this report must be derivable from collected data.
  No invented trends. No exaggerated certainty. No fabricated statistics.
  If a claim is uncertain, it is marked as such.

Insight generation rules:
  Insights are generated by applying templates to real numbers and entity
  names from the database. This is deterministic and transparent — not AI.
  When LLM-based insight generation is added, it will be clearly labelled
  and will receive the same data as context.
"""

import json
import logging
from datetime import datetime, timezone
from typing import Optional

import database
from database import decode_json, encode_json
from knowledge_graph import graph as kg
from models import WeeklyReport

logger = logging.getLogger(__name__)


class ReportGenerator:
    """
    Generates weekly intelligence reports from database contents.

    Usage:
        generator = ReportGenerator()
        report = generator.generate(week_key="2026-W28")
        generator.persist(report)
    """

    def generate(self, week_key: Optional[str] = None) -> WeeklyReport:
        """
        Generate a complete weekly intelligence report.

        Args:
            week_key: ISO week string, e.g. "2026-W28". Defaults to current week.

        Returns:
            WeeklyReport with full structured content.
        """
        if not week_key:
            now = datetime.now(timezone.utc)
            week_key = f"{now.isocalendar().year}-W{now.isocalendar().week:02d}"

        period_start, period_end = self._week_bounds(week_key)

        logger.info(f"Generating report for {week_key}")

        # Gather all data needed for the report
        signal_stats  = self._get_signal_stats(week_key)
        opportunities = self._get_week_opportunities(week_key)
        entity_summary = kg.weekly_entity_summary(week_key)
        top_pairs     = kg.co_occurring_pairs(min_weight=1.0, limit=5)

        # Build structured content
        top_opps = opportunities[:5]
        gold_opps   = [o for o in opportunities if o.get("tier") == "gold"]
        silver_opps = [o for o in opportunities if o.get("tier") == "silver"]

        insights = self._generate_insights(
            opportunities=opportunities,
            signal_stats=signal_stats,
            entity_summary=entity_summary,
            top_pairs=top_pairs,
        )

        recommended_actions = self._generate_actions(top_opps)

        content = {
            "week_key":     week_key,
            "period_start": period_start,
            "period_end":   period_end,
            "summary": {
                "total_signals":    signal_stats["total"],
                "sources_active":   signal_stats["sources"],
                "opportunities":    len(opportunities),
                "gold_count":       len(gold_opps),
                "silver_count":     len(silver_opps),
                "entities_in_graph": entity_summary["total_entities"],
            },
            "top_opportunities": top_opps,
            "key_insights":      insights,
            "recommended_actions": recommended_actions,
            "entity_intelligence": {
                "top_markets":      self._top_by_type(entity_summary, "market"),
                "top_technologies": self._top_by_type(entity_summary, "technology"),
                "top_problems":     self._top_by_type(entity_summary, "problem"),
                "strongest_pairs":  top_pairs,
            },
            "signal_breakdown": signal_stats["by_source"],
            "top_tags":        signal_stats["top_tags"],
            "generated_at":    datetime.now(timezone.utc).isoformat(),
        }

        return WeeklyReport(
            week_key=week_key,
            period_start=period_start,
            period_end=period_end,
            content=content,
            opp_count=len(opportunities),
            signal_count=signal_stats["total"],
        )

    def persist(self, report: WeeklyReport) -> bool:
        """
        Write a weekly report to the database.

        Uses INSERT OR REPLACE (last-write-wins within a week_key).
        Returns True if persisted, False on error.
        """
        with database.get_connection() as conn:
            try:
                conn.execute(
                    """
                    INSERT OR REPLACE INTO reports
                      (id, week_key, period_start, period_end, content,
                       opp_count, signal_count, created_at)
                    VALUES
                      (:id, :week_key, :period_start, :period_end, :content,
                       :opp_count, :signal_count, :created_at)
                    """,
                    {
                        "id":           report.id,
                        "week_key":     report.week_key,
                        "period_start": report.period_start,
                        "period_end":   report.period_end,
                        "content":      encode_json(report.content),
                        "opp_count":    report.opp_count,
                        "signal_count": report.signal_count,
                        "created_at":   report.created_at,
                    }
                )
                conn.commit()
                logger.info(f"Report persisted for {report.week_key}")
                return True
            except Exception as e:
                logger.error(f"Failed to persist report: {e}")
                return False

    # ── Insight generation (deterministic, evidence-based) ─────────────────

    def _generate_insights(
        self,
        opportunities: list[dict],
        signal_stats: dict,
        entity_summary: dict,
        top_pairs: list[dict],
    ) -> list[str]:
        """
        Generate human-readable insights from collected data.

        Rules:
          - Every insight is derived from a specific measurable data point.
          - Uncertainty is stated explicitly ("appears to be", "may indicate").
          - No invented trends. No exaggerated confidence.
          - Each insight is one sentence, concrete and actionable.
        """
        insights: list[str] = []
        n_signals = signal_stats["total"]
        n_sources = len(signal_stats["sources"])
        n_opps    = len(opportunities)
        gold_opps = [o for o in opportunities if o.get("tier") == "gold"]

        # Signal volume insight
        if n_signals > 0:
            source_list = ", ".join(sorted(signal_stats["sources"]))
            insights.append(
                f"{n_signals} signal{'s' if n_signals != 1 else ''} collected "
                f"from {n_sources} independent source{'s' if n_sources != 1 else ''} "
                f"({source_list}) — cross-source validation is active."
            )

        # Gold opportunity insight
        if gold_opps:
            top = gold_opps[0]
            insights.append(
                f"{len(gold_opps)} Gold-tier opportunit{'ies' if len(gold_opps) > 1 else 'y'} "
                f"detected this week. Top score: {top['composite_score']:.1f}/10 — "
                f"\"{top['title']}\"."
            )
        elif n_opps > 0:
            insights.append(
                f"{n_opps} Silver/Bronze-tier opportunit{'ies' if n_opps > 1 else 'y'} "
                f"detected. No Gold-tier patterns yet — "
                f"increase signal volume by adding more data sources."
            )
        else:
            insights.append(
                "No opportunities scored above the persistence threshold this week. "
                "Run the pipeline with more sources to increase signal diversity."
            )

        # Cross-source pattern insight
        cross_source = [
            o for o in opportunities
            if o.get("scores", {}).get("confidence", 0) >= 6.0
        ]
        if cross_source:
            insights.append(
                f"{len(cross_source)} opportunit{'ies' if len(cross_source) > 1 else 'y'} "
                f"confirmed across multiple sources (confidence ≥ 6.0). "
                f"Cross-source patterns have a higher probability of representing real demand."
            )

        # Entity co-occurrence insight
        if top_pairs:
            pair = top_pairs[0]
            insights.append(
                f"Strongest entity connection this week: "
                f"\"{pair['from']['name']}\" ↔ \"{pair['to']['name']}\" "
                f"(co-occurrence weight: {pair['weight']:.0f}). "
                f"Opportunities connecting both may be particularly well-positioned."
            )

        # Knowledge graph growth insight
        total_entities = entity_summary.get("total_entities", 0)
        if total_entities > 0:
            by_type = entity_summary.get("entities_by_type", {})
            dominant_type = max(by_type, key=by_type.get) if by_type else None
            if dominant_type:
                insights.append(
                    f"Knowledge graph contains {total_entities} entities. "
                    f"Dominant category: {dominant_type} ({by_type[dominant_type]} entities). "
                    f"The graph will improve scoring accuracy as it grows."
                )

        return insights

    def _generate_actions(self, top_opps: list[dict]) -> list[dict]:
        """
        Generate specific, evidence-backed action recommendations.
        One action per top opportunity, in score order.
        """
        action_templates = {
            "gold":   "Act this week. Build a minimum viable offer and send 10 targeted outreaches.",
            "silver": "Validate first. Spend 2 hours confirming competition depth before building.",
            "bronze": "Add to watch list. Check again next week for score improvement.",
        }

        actions = []
        for opp in top_opps:
            tier = opp.get("tier", "bronze")
            actions.append({
                "opportunity_id":    opp["id"],
                "opportunity_title": opp["title"],
                "composite_score":   opp["composite_score"],
                "tier":              tier,
                "action":            action_templates.get(tier, action_templates["bronze"]),
                "evidence_count":    opp.get("scores", {}).get("evidence_count", 0),
            })

        return actions

    # ── Data queries ──────────────────────────────────────────────────────

    def _get_signal_stats(self, week_key: str) -> dict:
        with database.get_connection() as conn:
            total = conn.execute(
                "SELECT COUNT(*) FROM signals"
            ).fetchone()[0]

            by_source_rows = conn.execute(
                "SELECT source, COUNT(*) as count FROM signals GROUP BY source"
            ).fetchall()

            tag_rows = conn.execute(
                "SELECT tags FROM signals WHERE collected_at >= datetime('now', '-7 days')"
            ).fetchall()

        by_source = {r["source"]: r["count"] for r in by_source_rows}

        tag_counts: dict[str, int] = {}
        for row in tag_rows:
            for tag in decode_json(row["tags"], []):
                tag_counts[tag] = tag_counts.get(tag, 0) + 1

        top_tags = sorted(tag_counts.items(), key=lambda x: x[1], reverse=True)[:8]

        return {
            "total":      total,
            "sources":    set(by_source.keys()),
            "by_source":  by_source,
            "top_tags":   [{"tag": t, "count": c} for t, c in top_tags],
        }

    def _get_week_opportunities(self, week_key: str) -> list[dict]:
        with database.get_connection() as conn:
            rows = conn.execute(
                """
                SELECT id, title, description, composite_score,
                       status, scores, week_key, created_at
                FROM   opportunities
                WHERE  status != 'dismissed'
                ORDER  BY composite_score DESC
                LIMIT  20
                """,
            ).fetchall()

        result = []
        for row in rows:
            scores = decode_json(row["scores"], {})
            tier   = (
                "gold"   if row["composite_score"] >= 8.0 else
                "silver" if row["composite_score"] >= 6.5 else
                "bronze"
            )
            result.append({
                "id":              row["id"],
                "title":           row["title"],
                "description":     row["description"],
                "composite_score": round(row["composite_score"], 2),
                "tier":            tier,
                "status":          row["status"],
                "scores":          scores,
                "week_key":        row["week_key"],
                "created_at":      row["created_at"],
            })
        return result

    @staticmethod
    def _top_by_type(entity_summary: dict, entity_type: str) -> list[dict]:
        """Return top entities of a given type from the summary."""
        top = entity_summary.get("top_entities", [])
        return [e for e in top if e.get("type") == entity_type][:5]

    # ── Date helpers ──────────────────────────────────────────────────────

    @staticmethod
    def _week_bounds(week_key: str) -> tuple[str, str]:
        """
        Return ISO 8601 start and end dates for a week_key like '2026-W28'.
        Week starts on Monday. End is Sunday 23:59:59 UTC.
        """
        try:
            year, week_num = week_key.split("-W")
            # ISO week date: year-W{ww}-1 = Monday
            monday = datetime.strptime(f"{year}-W{week_num}-1", "%G-W%V-%u")
            sunday = datetime.strptime(f"{year}-W{week_num}-7", "%G-W%V-%u")
            return (
                monday.strftime("%Y-%m-%dT00:00:00Z"),
                sunday.strftime("%Y-%m-%dT23:59:59Z"),
            )
        except (ValueError, AttributeError):
            now = datetime.now(timezone.utc)
            return now.strftime("%Y-%m-%dT00:00:00Z"), now.strftime("%Y-%m-%dT23:59:59Z")
