"""
report/generator.py — Weekly intelligence report generator

This is the system's primary output artifact. Every week it produces a
structured briefing that answers three questions:

  1. What did I observe? (signals, sources, volume)
  2. What does it mean? (opportunities, entities, patterns)
  3. What should I do next? (ranked actions with evidence)

The report is stored in the database (reports table) and served via the API.
It is also the natural input for future modules: the Business Generator would
read a report to draft business model outlines; the Execution Agent would read
it to draft outreach messages.

Design constraint:
  Every sentence in this report must be derivable from collected data.
  No invented trends. No exaggerated certainty. No fabricated statistics.
  If a claim is uncertain, it is marked as such.

Insight generation rules:
  All narrative text is generated by applying templates to real numbers,
  scorer reasons, and entity names — deterministic and transparent, not
  AI. When LLM-based generation is added, it will be clearly labelled and
  will receive the same underlying data as context. The narrative-building
  logic itself lives in opportunity_engine/explainer.py and
  knowledge_graph/insights.py — this file's job is gathering data
  (including the previous period's report, for historical comparison) and
  assembling it into a WeeklyReport.

Editorial stance:
  The report reads as an analyst briefing, not a data export. Executive
  summary leads with business meaning ("an emerging opportunity around X,
  with genuine demand and low competition") rather than measurements ("8
  signals from 3 sources"). Internal scores (0-10 dimension values) are
  preserved for anyone who wants them under each opportunity's
  supporting_data, but the primary content a person reads is prose:
  market context, market gap, business potential, risks, and confidence —
  each grounded in a real scorer reason or a real historical comparison,
  never invented. See explainer.py's module docstring for the full detail
  on this editorial stance and its constraints.

Intelligence brief upgrade:
  The report used to expose technical metrics (signal counts, JSON score
  blobs) with little explanation of why any of it matters. The content
  now also includes an executive_summary, trend_analysis, per-opportunity
  narrative explanations, and — when nothing qualified — a
  zero_opportunities_explanation naming the strongest near-misses and why
  they fell short. All of this narrative work lives in
  opportunity_engine/explainer.py and knowledge_graph/insights.py; this
  file's job is still just to gather data and assemble content, unchanged
  from its original design.
"""

import json
import logging
from datetime import datetime, timezone
from typing import Optional

import database
from database import decode_json, encode_json
from knowledge_graph import graph as kg
from knowledge_graph.insights import explain_pair
from models import Signal, WeeklyReport
from opportunity_engine import explainer
from opportunity_engine.detector import PatternDetector

logger = logging.getLogger(__name__)


class ReportGenerator:
    """
    Generates weekly intelligence reports from database contents.

    Usage:
        generator = ReportGenerator()
        report = generator.generate(week_key="2026-W28")
        generator.persist(report)
    """

    def generate(
        self,
        week_key: Optional[str] = None,
        domain: str = "business",
    ) -> WeeklyReport:
        """
        Generate a complete weekly intelligence report for one domain.

        Args:
            week_key: ISO week string, e.g. "2026-W28". Defaults to current week.
            domain:   The domain to report on. Every active domain gets its
                      own report per week — see pipeline.py.

        Returns:
            WeeklyReport with full structured content, scoped to `domain`.
        """
        if not week_key:
            now = datetime.now(timezone.utc)
            week_key = f"{now.isocalendar().year}-W{now.isocalendar().week:02d}"

        period_start, period_end = self._week_bounds(week_key)

        logger.info(f"Generating report for {week_key} [{domain}]")

        # Gather all data needed for the report
        signal_stats  = self._get_signal_stats(week_key, domain)
        opportunities = self._get_week_opportunities(week_key, domain)
        entity_summary = kg.weekly_entity_summary(week_key)
        top_pairs     = kg.co_occurring_pairs(min_weight=1.0, limit=5)
        week_signals  = self._get_week_signals(period_start, period_end, domain)
        signals_by_id = {s.id: s for s in week_signals}

        top_opps    = opportunities[:5]
        gold_opps   = [o for o in opportunities if o.get("tier") == "gold"]
        silver_opps = [o for o in opportunities if o.get("tier") == "silver"]

        # Look at last period's report (if any) to support recurrence-aware
        # narrative and the comparison_to_last_period section. None of this
        # invents anything — it's a real diff against a persisted report,
        # or explicitly absent when there's nothing to compare against.
        previous_content = self._get_previous_report(week_key, domain)
        previous_opportunities = (previous_content or {}).get("opportunities", [])
        previous_pairs = (previous_content or {}).get("entity_intelligence", {}).get("strongest_pairs")

        # Explain each top opportunity as an analyst would: narrative
        # analysis + concrete next actions, with recurrence context when
        # a matching opportunity existed last period.
        explained_opportunities = []
        for opp in top_opps:
            match = explainer.match_previous_opportunity(opp.get("title", ""), previous_opportunities)
            recurrence = None
            if match is not None:
                prev_recurrence = (match.get("supporting_data") or {}).get("recurrence") or {}
                weeks_seen = prev_recurrence.get("weeks_seen", 1) + 1
                delta = opp.get("composite_score", 0.0) - match.get("composite_score", 0.0)
                direction = "growing" if delta > 0.3 else "fading" if delta < -0.3 else "stable"
                recurrence = {"weeks_seen": weeks_seen, "direction": direction}
            cluster_signals = [signals_by_id[sid] for sid in opp.get("signal_ids", []) if sid in signals_by_id]
            explained = explainer.explain_opportunity(opp, cluster_signals, recurrence=recurrence)
            # Carried so *next* period's report can continue the recurrence
            # chain (weeks_seen keeps counting up) — not narrative content,
            # kept alongside the other drill-down data in supporting_data.
            explained["supporting_data"]["recurrence"] = recurrence
            explained_opportunities.append(explained)

        # If nothing qualified this period, explain why instead of just
        # reporting zero.
        zero_explanation = None
        if not opportunities:
            diagnostics = PatternDetector().diagnose(week_signals, domain=domain)
            zero_explanation = explainer.explain_zero_opportunities(
                diagnostics.rejected, total_signals=signal_stats["total"],
            )

        trend_analysis = explainer.build_trend_analysis(
            week_signals, top_pairs, previous_pairs=previous_pairs,
        )

        comparison = explainer.build_historical_comparison(
            current_stats=signal_stats,
            current_opportunities=opportunities,
            previous_content=previous_content,
        )

        executive_summary = explainer.build_executive_summary(
            signal_stats=signal_stats,
            explained_opportunities=explained_opportunities,
            trends=trend_analysis,
            zero_opps_explanation=zero_explanation,
            comparison=comparison,
        )

        narrative_connections = [explain_pair(pair) for pair in top_pairs[:5]]

        content = {
            "week_key":     week_key,
            "period_start": period_start,
            "period_end":   period_end,
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "executive_summary": executive_summary,
            "opportunities":     explained_opportunities,
            "zero_opportunities_explanation": zero_explanation,
            "trend_analysis":    trend_analysis,
            "comparison_to_last_period": comparison,
            "summary": {
                "total_signals":     signal_stats["total"],
                "sources_active":    signal_stats["sources"],
                "opportunities":     len(opportunities),
                "gold_count":        len(gold_opps),
                "silver_count":      len(silver_opps),
                "entities_in_graph": entity_summary["total_entities"],
            },
            "entity_intelligence": {
                "top_markets":      self._top_by_type(entity_summary, "market"),
                "top_technologies": self._top_by_type(entity_summary, "technology"),
                "top_problems":     self._top_by_type(entity_summary, "problem"),
                "strongest_pairs":  top_pairs,
                "narrative_connections": narrative_connections,
            },
            "signal_breakdown": signal_stats["by_source"],
            "top_tags":         signal_stats["top_tags"],
        }

        return WeeklyReport(
            week_key=week_key,
            period_start=period_start,
            period_end=period_end,
            content=content,
            opp_count=len(opportunities),
            signal_count=signal_stats["total"],
            domain=domain,
        )

    def persist(self, report: WeeklyReport) -> bool:
        """
        Write a weekly report to the database.

        Uses INSERT OR REPLACE (last-write-wins within a week_key).
        Returns True if persisted, False on error.
        """
        with database.get_connection() as conn:
            try:
                # INSERT OR REPLACE keys off the (week_key, domain) unique
                # index — see database.py's idx_reports_week_domain. This is
                # what lets every active domain persist its own report for
                # the same week without overwriting another domain's report.
                conn.execute(
                    """
                    INSERT OR REPLACE INTO reports
                      (id, week_key, period_start, period_end, content,
                       opp_count, signal_count, created_at, domain)
                    VALUES
                      (:id, :week_key, :period_start, :period_end, :content,
                       :opp_count, :signal_count, :created_at, :domain)
                    """,
                    {
                        "id":           report.id,
                        "week_key":     report.week_key,
                        "period_start": report.period_start,
                        "period_end":   report.period_end,
                        "content":      encode_json(report.content),
                        "opp_count":    report.opp_count,
                        "signal_count": report.signal_count,
                        "created_at":   report.created_at,
                        "domain":       report.domain,
                    }
                )
                conn.commit()
                logger.info(f"Report persisted for {report.week_key} [{report.domain}]")
                return True
            except Exception as e:
                logger.error(f"Failed to persist report: {e}")
                return False

    # ── Historical comparison helpers ───────────────────────────────────────

    def _get_previous_report(self, week_key: str, domain: str) -> Optional[dict]:
        """
        Fetch the previous period's report content for this domain, if one
        exists. Returns None (not a fabricated comparison) when there's
        nothing to compare against — e.g. the first tracked week.
        """
        prev_week_key = self._previous_week_key(week_key)
        with database.get_connection() as conn:
            row = conn.execute(
                "SELECT content FROM reports WHERE week_key = ? AND domain = ?",
                (prev_week_key, domain),
            ).fetchone()
        if row is None:
            return None
        return decode_json(row["content"], None)

    @staticmethod
    def _previous_week_key(week_key: str) -> str:
        """
        Return the ISO week_key immediately before the given one, correctly
        handling year boundaries (e.g. 2026-W01 -> 2025-W52/53).
        """
        from datetime import date, timedelta
        year, week_num = week_key.split("-W")
        monday = date.fromisocalendar(int(year), int(week_num), 1)
        prev_monday = monday - timedelta(days=7)
        prev_year, prev_week, _ = prev_monday.isocalendar()
        return f"{prev_year}-W{prev_week:02d}"

    # ── Data queries ──────────────────────────────────────────────────────

    def _get_signal_stats(self, week_key: str, domain: str) -> dict:
        with database.get_connection() as conn:
            total = conn.execute(
                "SELECT COUNT(*) FROM signals WHERE domain = ?", (domain,)
            ).fetchone()[0]

            by_source_rows = conn.execute(
                "SELECT source, COUNT(*) as count FROM signals "
                "WHERE domain = ? GROUP BY source",
                (domain,),
            ).fetchall()

            tag_rows = conn.execute(
                "SELECT tags FROM signals "
                "WHERE domain = ? AND collected_at >= datetime('now', '-7 days')",
                (domain,),
            ).fetchall()

        by_source = {r["source"]: r["count"] for r in by_source_rows}

        tag_counts: dict[str, int] = {}
        for row in tag_rows:
            for tag in decode_json(row["tags"], []):
                tag_counts[tag] = tag_counts.get(tag, 0) + 1

        top_tags = sorted(tag_counts.items(), key=lambda x: x[1], reverse=True)[:8]

        return {
            "total":      total,
            "sources":    sorted(by_source.keys()),
            "by_source":  by_source,
            "top_tags":   [{"tag": t, "count": c} for t, c in top_tags],
        }

    def _get_week_opportunities(self, week_key: str, domain: str) -> list[dict]:
        with database.get_connection() as conn:
            rows = conn.execute(
                """
                SELECT id, title, description, composite_score,
                       status, scores, week_key, created_at, signal_ids
                FROM   opportunities
                WHERE  status != 'dismissed' AND domain = :domain
                ORDER  BY composite_score DESC
                LIMIT  20
                """,
                {"domain": domain},
            ).fetchall()

        result = []
        for row in rows:
            scores = decode_json(row["scores"], {})
            tier   = (
                "gold"   if row["composite_score"] >= 8.0 else
                "silver" if row["composite_score"] >= 6.5 else
                "bronze"
            )
            result.append({
                "id":              row["id"],
                "title":           row["title"],
                "description":     row["description"],
                "composite_score": round(row["composite_score"], 2),
                "tier":            tier,
                "status":          row["status"],
                "scores":          scores,
                "week_key":        row["week_key"],
                "created_at":      row["created_at"],
                "signal_ids":      decode_json(row["signal_ids"], []),
            })
        return result

    def _get_week_signals(self, period_start: str, period_end: str, domain: str) -> list[Signal]:
        """
        Reconstruct Signal objects collected within this report's period for
        this domain. Needed by the explanation layer (trend analysis,
        opportunity evidence, and zero-opportunity diagnostics) — those need
        actual signal text and engagement, not just aggregate counts.

        Read-only and best-effort: any row that somehow fails Signal's own
        construction validation (e.g. a legacy blank-title row) is skipped
        rather than failing the whole report.
        """
        with database.get_connection() as conn:
            rows = conn.execute(
                """
                SELECT id, source, source_id, url, title, content,
                       platform_score, comment_count, entity_ids, tags,
                       raw_metadata, collected_at, processed, domain
                FROM   signals
                WHERE  domain = ? AND collected_at BETWEEN ? AND ?
                """,
                (domain, period_start, period_end),
            ).fetchall()

        signals: list[Signal] = []
        for row in rows:
            try:
                signals.append(Signal(
                    id=row["id"],
                    source=row["source"],
                    source_id=row["source_id"],
                    url=row["url"] or "",
                    title=row["title"],
                    content=row["content"] or "",
                    platform_score=row["platform_score"] or 0,
                    comment_count=row["comment_count"] or 0,
                    entity_ids=decode_json(row["entity_ids"], []),
                    tags=decode_json(row["tags"], []),
                    raw_metadata=decode_json(row["raw_metadata"], {}),
                    collected_at=row["collected_at"],
                    processed=row["processed"] or 0,
                    domain=row["domain"],
                ))
            except ValueError as e:
                logger.warning(f"Skipping malformed signal row {row['id']}: {e}")
                continue
        return signals

    @staticmethod
    def _top_by_type(entity_summary: dict, entity_type: str) -> list[dict]:
        """Return top entities of a given type from the summary."""
        top = entity_summary.get("top_entities", [])
        return [e for e in top if e.get("type") == entity_type][:5]

    # ── Date helpers ──────────────────────────────────────────────────────

    @staticmethod
    def _week_bounds(week_key: str) -> tuple[str, str]:
        """
        Return ISO 8601 start and end dates for a week_key like '2026-W28'.
        Week starts on Monday. End is Sunday 23:59:59 UTC.
        """
        try:
            year, week_num = week_key.split("-W")
            # ISO week date: year-W{ww}-1 = Monday
            monday = datetime.strptime(f"{year}-W{week_num}-1", "%G-W%V-%u")
            sunday = datetime.strptime(f"{year}-W{week_num}-7", "%G-W%V-%u")
            return (
                monday.strftime("%Y-%m-%dT00:00:00Z"),
                sunday.strftime("%Y-%m-%dT23:59:59Z"),
            )
        except (ValueError, AttributeError):
            now = datetime.now(timezone.utc)
            return now.strftime("%Y-%m-%dT00:00:00Z"), now.strftime("%Y-%m-%dT23:59:59Z")
